name: Deploy

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: 
        git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: Add changes
      run:
        git add . 
    - name: Commit changes
      run: 
        git commit -m ${{ github.sha }}
    - name: Push changes
      run:
        git push -f heroku master
